package main

import "fmt"

// EN GO TENEMOS DOS TIPO DE COMENTARIO

//* 1.- LOS COMENTARIOS EN UNA SOLA LIENA COMO ESTE

/*
	Y TAMBIEN HAY COMENTARIOS
	MULTILINEA
	O
	EN
	BLOQUE
*/
func main() {

	//! COMO BUENAS PRACTICAS PARA EL USO DE LOS COMENTARIOS Y TENER UNA DOCUMENTACION EN EL CODIGO, EN GO SE RECOMEIENDO HACER UNA PEQUENA MENCION DE QUE HACE CADA BLOQUE... POR EJEMPLO:

	// PerfilGitHub ES EL SIITO OFICIA DEL REPOSITIORIO
	const PerfilGitHub = "https://github.com/LOctavioDev"

	// SON CONSTANTES DE NUMEROS
	const (
		zero = iota
		one
		two
		three
	)

	fmt.Println(zero, one, two, three)

	// SI QUIER VER LA DOCUMENTACION QUE CREASTE CON LOS COMENTARIOS TIENE QUE ESCRIBIR EL SIGUIENTO COMANDO
	// TIENES QUE ESTAR EN EL MISMO DIRECTORIO DEL ARCHIVO GO ... "go doc -all"

}
