// CUALQUIER ARCHIVO DE GO SIEMPRE EN SU PRIMERA LINEA DEBEMOS EL NOMBRE DEL PAQUETE.
package main

import "fmt"

// EL PAQUETE MAIN SIEMPRE NECESITA UNA FUNCION QUE SE LLAME MAIN.

//ESTO ES PARA QUE LAS INSTRUCCIONES QUE ESTEN DENTRO DEL MAIN SE EJECUTEN CUANDO LEVANTEMOS NUESTRA APLIACION. LO PODEMOS VER COMO EL PUNTO DE ENTRADA DE NUESTRO PROGRAMA.

func main() { 

// PARA DECLARAR VARIABLES EN GO NECESITAMOS UTILIZAR LA PALABRA RESERVADA 'var' Y LUEGO DE ESO PONER EL NOMBRE DE LA VARIABLE.

// ! RECORDAR QUE GO ES UN LENGUAJE ESTATICO A DIFERENCIA DE JAVASCRIPT O PYTHON. ENTONCES DEBEMOS DE INDICAR EL TIPO DE LA VARIABLE. 
	var apple string 
	
	// LUEGO PODEMOS ASIGNAR EL VALOR

	apple = "🍎" // ! LOS STRING EN GO SIEMPRE DEBEN DE ESTAR CON COMILLAS DOBLES 

	// ? SI EN ESTE PUNTO INTENAMOS EJECUTAR EL PROGRAMA ASI, NOS MANDARA UN ERROR PORQUE LA VARIABLE NO ESTA SIENDO USADA. EN GO NO PODEMOS DECLARAR VARIABLES SIN USAR.

	// PERO SI USAMOS LA VARIABLE APPLE, EJECUTAREMOS EL PROGRAMA CORRECTAMENTE.
	fmt.Println(apple)


	// AL IGUAL QUE EN OTROS LENGAUJES PUEDES ASIGNAR UN VALOR AL MOMENTO DE DECLARARLA.
	var banana = "🍌"
	var orange = "🍊"
	var lemon = "🍋"

	fmt.Println(banana, orange, lemon)

	// GO NOS PERMITE ALGO... LO CUAL ES AGRUPAR LAS VARIABLES
	// PARA HACERLO DEBEMOS PONER LA PALABRA RESERVADA 'var' SEGUIDO DE UN PARENTESIS Y ADENTRO PONER LOS NOMBRES DE LAS VARIABLES Y ASIGANCIONES.

	var (
		grapes string = "🍇"
		kiwi string = "🥝"
		watermelon string = "🍉"
	)

	fmt.Println(grapes, kiwi, watermelon)

	// SI LO QUIERES HACER QUE EN UNA SOLA LINEA PUEDAS ASIGNAR TUS TRES VARIABLES Y ASIGANCIONARLAS AL MISMO TIEMPO SE PUEDE HACER DE LA SIGUIENTE MANERA.
	var pineapole, pear, cherry string = "🍍", "🍐", "🍒"

	fmt.Println(pineapole, pear, cherry)

	// * GO A PESAR DE QUE ES UN LENGUAJE ESTATICO, TIENE CIERTAS CARACTERISTICAS DE LENGUAJES DINAMICOS. EN ESTE CASO TENEMOS POR EJEMPLO EL OPERADOR SE 'asignacion de variable corta' o sea ' =: ' Y CON ESTE OPERADOR HACE QUE NO NECESITEMOS USAR LA PALABRA RESERVADA 'var' NI EL TIPO DE DATO COMP 'string' 

	orange = "🍊"

	fmt.Println(orange)

}